#!/bin/bash 

# extract the bodies of the avro data.

# sed extract body
# sort sorts
# awk points out start, stops, and sequence discontinuities

sed 's/.*"body":"\(.*\)","timestamp".*/\1/' | sort | uniq
