#!/bin/bash 

# extract the bodies of the avro data.

# sed extract body
# sort sorts
# awk points out start, stops, and sequence discontinuities

sed 's/.*"body":"\(.*\)"."timestamp".*/\1/' | sort | uniq -c | awk "{ if (NR==1) print \"start:\t\"\$2,\$3,\$1}  {if (FNR!=\$2) print \"discontinuity:\", FNR, \$2, \$4 ; FNR=\$2 +0 } {if (\$1!=1) print \"dupes:\t\", \$2,\$3,\$1 } END { print\"end:\t\",\$2,\$3,\$1}"
